version: "3"

services:
  sirius:
    ports:
      - 5000:5000
    depends_on:
      - sirius-database
    command: ["/bin/wait-for-it.sh", "db:5342", "--", "./manage.py db upgrade"]
    environment:
      - VIRTUAL_HOST=sirius.localhost

  sirius-database:
    image: postgres
    healthcheck:
      test: "exit 0"
    ports:
      - "32770:5432"
    environment:
      - POSTGRES_PASSWORD=plop

  sirius-web:
    ports:
      - "8880:80"
      - "8443:443"
