version: "3"

services:
  sirius:
    depends_on:
      - sirius-database-test
    ports:
      - 5000:5000
    command: "bin/wait-for-it.sh sirius-database-test:5432 -- bin/docker-entrypoint.sh"
    environment:
      - DATABASE_URL=postgresql://postgres:plop@sirius-database-test/sirius-test

  sirius-database-test:
    container_name: sirius-database-test
    image: postgres
    healthcheck:
      test: "exit 0"
    environment:
      - POSTGRES_DB=sirius-test
      - POSTGRES_PASSWORD=plop

  sirius-web:
    ports:
      - "8880:80"
      - "8443:443"
