version: "3"

services:
  sirius:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: "./manage.py db upgrade"

  sirius-web:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - sirius
