version: "3"

services:
  sirius:
    ports:
      - 5000:5000
    depends_on:
      - sirius-database
    command:
      [
        "bin/wait-for-it.sh",
        "sirius-database:5432",
        "--",
        "bin/docker-entrypoint.sh",
      ]
    environment:
      - VIRTUAL_HOST=sirius.localhost

  sirius-database:
    image: postgres
    healthcheck:
      test: "exit 0"
    ports:
      - "32770:5432"
    environment:
      - POSTGRES_DB=sirius-dev
      - POSTGRES_PASSWORD=plop

  sirius-web:
    ports:
      - "8880:80"
      - "8443:443"
